In [3]:
import pandas as pd

movies = pd.read_csv("../data/raw/IMDB-Movie-Dataset(2023-1951).csv")

In [4]:
movies.isnull().sum()

Unnamed: 0     0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
dtype: int64

In [5]:
movies["year"] = movies["year"].fillna("Unknown")

In [6]:
movies = movies[
    ["movie_name",
     "year",
     "genre",
     "overview",
     "director",
     "cast"
     ]
]

In [7]:
movies.head()

,movie_name,year,genre,overview,director,cast
0,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [8]:
movies["movie_name"] = movies["movie_name"].str.lower()
movies["genre"] = movies["genre"].str.lower()
movies["overview"] = movies["overview"].str.lower()
movies["director"] = movies["director"].str.lower()
movies["cast"] = movies["cast"].str.lower()

In [9]:
movies["movie_name"] = movies["movie_name"].str.strip()
movies["director"] = movies["director"].str.strip()
movies["cast"] = movies["cast"].str.strip()
movies["genre"] = movies["genre"].str.strip()

In [10]:
movies["genre"] = movies["genre"].str.replace(", ", " ")
movies["cast"] = movies["cast"].str.replace(", ", " ")

In [11]:
movies.head()

,movie_name,year,genre,overview,director,cast
0,jawan,2023,action thriller,a high-octane action thriller which outlines t...,atlee,shah rukh khan nayanthara vijay sethupathi dee...
1,jaane jaan,2023,crime drama mystery,a single mother and her daughter who commit a ...,sujoy ghosh,kareena kapoor jaideep ahlawat vijay varma sau...
2,jailer,2023,action comedy crime,a retired jailer goes on a manhunt to find his...,nelson dilipkumar,rajinikanth mohanlal shivarajkumar jackie shroff
3,rocky aur rani kii prem kahaani,2023,comedy drama family,flamboyant punjabi rocky and intellectual beng...,karan johar,ranveer singh alia bhatt dharmendra shabana azmi
4,omg 2,2023,comedy drama,an unhappy civilian asks the court to mandate ...,amit rai,pankaj tripathi akshay kumar yami gautam pawan...

In [12]:
movies["tags"] = (
    movies["genre"] + " " +
    movies["overview"] + " " +
    movies["director"] + " " +
    movies["cast"] + " " 
)

In [13]:
new_df = movies[
    ["movie_name", "year", "tags"]
]
print(new_df.head())

                        movie_name  year  \
0                            jawan  2023
1                       jaane jaan  2023
2                           jailer  2023
3  rocky aur rani kii prem kahaani  2023
4                            omg 2  2023

                                                tags
0  action thriller a high-octane action thriller ...
1  crime drama mystery a single mother and her da...
2  action comedy crime a retired jailer goes on a...
3  comedy drama family flamboyant punjabi rocky a...
4  comedy drama an unhappy civilian asks the cour...

In [14]:
new_df["tags"] = new_df["tags"].str.lower()

In [15]:
new_df.to_csv(
    "../data/processed/imdb_cleaned.csv",
    index=False
)

In [16]:
print(new_df.head(5))

                        movie_name  year  \
0                            jawan  2023
1                       jaane jaan  2023
2                           jailer  2023
3  rocky aur rani kii prem kahaani  2023
4                            omg 2  2023

                                                tags
0  action thriller a high-octane action thriller ...
1  crime drama mystery a single mother and her da...
2  action comedy crime a retired jailer goes on a...
3  comedy drama family flamboyant punjabi rocky a...
4  comedy drama an unhappy civilian asks the cour...

In [ ]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.10.0-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting click (from nltk)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.7.19-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.69.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\samiran\onedrive\desktop\movie recommendation system\movie_recommendation_system\venv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 2.1 MB/s eta 0:00:01
   ------------------------ --------------- 1.0/1.7 MB 2.4 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 2.0 MB/s  0:00:00
Downloading regex-2026.7.19-cp314-cp314-win_amd64.whl (280 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading tqdm-4.69.1-py3-none-any.whl (675 kB)
   ---------------------------------------- 0.0/675.5 kB ? eta -:--:--
   --------------- ------------------------ 262.1/675.5 kB ? eta -:--:--
   ---------------------------------------- 675.5/675.5 kB 2.0 MB/s  0:00:00
Installing collected packages: tqdm, regex, joblib, defusedxml, click, nltk

   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   ------------- -------------------------- 2/6 [joblib]
   -------------------- ------------------- 3/6 [defusedxml]
   -------------------- ------------------- 3/6 [defusedxml]
   -------------------------- ------------- 4/6 [click]
   -------------------------- ------------- 4/6 [click]
   -------------------------- ------------- 4/6 [click]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   --------------------------------- ------ 5/6 [nltk]
   ---------------------------------------- 6/6 [nltk]

Successfully installed click-8.4.2 defusedxml-0.7.1 joblib-1.5.3 nltk-3.10.0 regex-2026.7.19 tqdm-4.69.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import nltk
import string

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

In [19]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SAMIRAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
ps = PorterStemmer()

In [21]:
def preprocess(text):

    # convert to lowercase
    text = text.lower()

    # remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # split into words
    words = text.split()

    # remove stopwords
    words = [word for word in words if word not in stopwords.words("english")]

    # stemming
    words = [ps.stem(word) for word in words]

    return " ".join(words)

In [26]:
new_df["tags"] = new_df["tags"].apply(preprocess)

In [27]:
new_df["tags"].head()

0    action thriller highoctan action thriller outl...
1    crime drama mysteri singl mother daughter comm...
2    action comedi crime retir jailer goe manhunt f...
3    comedi drama famili flamboy punjabi rocki inte...
4    comedi drama unhappi civilian ask court mandat...
Name: tags, dtype: str

In [28]:
new_df.to_csv(
    "../data/processed/imdb_preprocessed.csv",
    index=False
)

In [29]:
new_df.loc[0, "tags"]

'action thriller highoctan action thriller outlin emot journey man set rectifi wrong societi atle shah rukh khan nayanthara vijay sethupathi deepika padukon'