In [1]:
import pandas as pd

movies = pd.read_csv("../data/processed/imdb_preprocessed.csv")

movies.head()

,movie_name,year,genre,tags
0,jawan,2023,action thriller,action thriller highoctan action thriller outl...
1,jaane jaan,2023,crime drama mystery,crime drama mysteri singl mother daughter comm...
2,jailer,2023,action comedy crime,action comedi crime retir jailer goe manhunt f...
3,rocky aur rani kii prem kahaani,2023,comedy drama family,comedi drama famili flamboy punjabi rocki inte...
4,omg 2,2023,comedy drama,comedi drama unhappi civilian ask court mandat...

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [3]:
from src.movie_filter import MovieFilter
from src.mood_classifier import MoodClassifier
from src.genre_mapper import MOOD_GENRES

In [4]:
user_input = "I had a stressful day."

In [7]:
classifier = MoodClassifier()

prediction = classifier.predict(user_input)

mood = prediction["mood"]
confidence = prediction["confidence"]

print("Predicted Mood:", mood)
print("Confidence:", confidence)

Predicted Mood: relaxed
Confidence: 1.0

In [8]:
genres = MOOD_GENRES[mood]
print(genres)

['comedy', 'family', 'drama']

In [9]:
movie_filter = MovieFilter(movies)

filtered_movies = movie_filter.filter_by_genres(genres)
filtered_movies.head()

,movie_name,year,genre,tags
1,jaane jaan,2023,crime drama mystery,crime drama mysteri singl mother daughter comm...
3,rocky aur rani kii prem kahaani,2023,comedy drama family,comedi drama famili flamboy punjabi rocki inte...
4,omg 2,2023,comedy drama,comedi drama unhappi civilian ask court mandat...
5,sukhee,2023,drama,drama much dismay husband middleclass housewif...
9,mastaney,2023,action drama history,action drama histori set 1739 nadar shah undef...

In [10]:
candidate_indices = filtered_movies.index.tolist()

print(candidate_indices[:10])

[1, 3, 4, 5, 9, 10, 11, 12, 13, 14]

In [11]:
print(filtered_movies.shape)

(1552, 4)

In [12]:
import pickle

with open("../models/tfidf_matrix.pkl", "rb") as file:

    tfidf_matrix = pickle.load(file)

In [13]:
from src.recommender import MovieRecommender

recommender = MovieRecommender(
    movies,
    tfidf_matrix
)

In [15]:
favourite_movie = input("Enter your favourite movie: ")

In [16]:
recommendations = recommender.recommend(
    mood_input=user_input,
    favourite_movie=favourite_movie,
    top_n=10
)

recommendations

Predicted Mood : relaxed
Mood Confidence : 100%
Selected Genres : ['comedy', 'family', 'drama']
Matched movie: pathaan (100.0%)
Matched Movie: pathaan

{'predicted_mood': 'relaxed',
 'matched_movie': 'pathaan',
 'recommendations':                           movie_name  year                   genre  \
 1711                   finding fanny  2014  adventure comedy drama
 336                         cocktail  2012    comedy drama romance
 325                        desi boyz  2011    comedy drama romance
 1617                         gardish  1993      action crime drama
 721                       the intern     V   comedy drama thriller
 440                bachna ae haseeno  2008    comedy drama romance
 411                      madras cafe  2013   action drama thriller
 53                      om shanti om  2007     action comedy drama
 148                       a thursday  2022          drama thriller
 2053  taxi no. 9 2 11: nau do gyarah  2006   comedy drama thriller

                                                    tags  similarity_score
 1711  adventur comedi drama man embark road trip fin...          0.249735
 336   comedi drama romanc love triangl guy two girl ...          0.182223
 325   comedi drama romanc two friend lose job part b...          0.177625
 1617  action crime drama soontob polic offic take pa...          0.166179
 721   comedi drama thriller indian adapt intern 2015...          0.158091
 440   comedi drama romanc raj heartbreak love stori ...          0.145551
 411   action drama thriller indian intellig agent jo...          0.141517
 53    action comedi drama 1970 om aspir actor murder...          0.139896
 148   drama thriller naina playschool teacher take 1...          0.136788
 2053  comedi drama thriller cabbi patekar businessma...          0.132464  }