In [1]:
import pandas as pd

movies = pd.read_csv("../data/processed/imdb_preprocessed.csv")

movies.head()

,movie_name,year,genre,tags
0,jawan,2023,action thriller,action thriller highoctan action thriller outl...
1,jaane jaan,2023,crime drama mystery,crime drama mysteri singl mother daughter comm...
2,jailer,2023,action comedy crime,action comedi crime retir jailer goe manhunt f...
3,rocky aur rani kii prem kahaani,2023,comedy drama family,comedi drama famili flamboy punjabi rocki inte...
4,omg 2,2023,comedy drama,comedi drama unhappi civilian ask court mandat...

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [3]:
from src.movie_filter import MovieFilter
from src.mood_classifier import MoodClassifier
from src.genre_mapper import MOOD_GENRES

In [4]:
user_input = "I had a stressful day."

In [5]:
classifier = MoodClassifier()

mood = classifier.predict(user_input)

print(mood)

relaxed

In [6]:
genres = MOOD_GENRES[mood]
print(genres)

['comedy', 'family', 'drama']

In [11]:
movie_filter = MovieFilter(movies)
print(movie_filter)

filtered_movies = movie_filter.filter_by_genres(genres)
filtered_movies.head()

<src.movie_filter.MovieFilter object at 0x0000017E93EFA490>

,movie_name,year,genre,tags
0,jaane jaan,2023,crime drama mystery,crime drama mysteri singl mother daughter comm...
1,rocky aur rani kii prem kahaani,2023,comedy drama family,comedi drama famili flamboy punjabi rocki inte...
2,omg 2,2023,comedy drama,comedi drama unhappi civilian ask court mandat...
3,sukhee,2023,drama,drama much dismay husband middleclass housewif...
4,mastaney,2023,action drama history,action drama histori set 1739 nadar shah undef...

In [12]:
candidate_indices = filtered_movies.index.tolist()

print(candidate_indices[:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
print(filtered_movies.shape)

(1552, 4)