In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().resolve().parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
import pandas as pd
import pickle
from src.recommender import MovieRecommender

In [3]:
movies = pd.read_csv("../data/processed/imdb_preprocessed.csv")

movies.head()

,movie_name,year,genre,tags
0,jawan,2023,action thriller,action thriller highoctan action thriller outl...
1,jaane jaan,2023,crime drama mystery,crime drama mysteri singl mother daughter comm...
2,jailer,2023,action comedy crime,action comedi crime retir jailer goe manhunt f...
3,rocky aur rani kii prem kahaani,2023,comedy drama family,comedi drama famili flamboy punjabi rocki inte...
4,omg 2,2023,comedy drama,comedi drama unhappi civilian ask court mandat...

In [4]:
with open("../models/tfidf_matrix.pkl", "rb") as file:
    tfidf_matrix = pickle.load(file)

In [5]:

recommender = MovieRecommender(
    movies,
    tfidf_matrix
)

In [6]:
user_mood = input("How are you feeling today? ")
favourite_movie = input("Enter your favourite movie: ")

In [7]:
result = recommender.recommend(
    mood_input=user_mood,
    favourite_movie=favourite_movie,
    top_n=10
)

Predicted Mood : relaxed
Selected Genres : ['comedy', 'family', 'drama']

ValueError: No movie found similar to ''.

In [ ]:
print("Predicted Mood:", result["predicted_mood"])
print("Matched Movie:", result["matched_movie"])

display(result["recommendations"])

Predicted Mood: happy
Matched Movie: pathaan

,movie_name,year,genre,tags,similarity_score
826,102 not out,2018,comedy drama,comedi drama 102 2018 comedydrama film legenda...,0.0
1428,jaggu ki lalten,2022,drama,drama jaggu ki lalten comedydrama music film e...,0.0